import configparser
from pathlib import Path

from .logger import log_error, logger
from .models import ConfigFile


def load_ini_as_dict(file_path: Path) -> dict:
    """Read an INI file and return its contents as a nested dictionary."""
    config = configparser.ConfigParser()
    # By default, keys are converted to lowercase - convert instead to uppercase to match the expected environment variable format
    # We need to silence an erroneous mypy error here (see https://github.com/python/mypy/issues/5062)
    config.optionxform = lambda option: option.upper()  # type: ignore

    try:
        config.read(file_path)
    except configparser.Error as err:
        log_error(logger, f"Error reading INI file: {err}")

    if not config.sections():
        return {}

    return {section: dict(config[section]) for section in config.sections()}


def write_config_to_env_file(config: ConfigFile, out_file: Path) -> None:
    """Write out configuration variables as key-value pairs in a .env file."""
    with open(out_file, "w", encoding="utf-8") as env_file:
        env_file.write(
            "# This .env file was auto-generated by configure-nb. Do not edit this file directly.\n"
        )
        for section_num, section_vars in enumerate(
            # exclude_none useful for experimental variables that we want to omit from the .env file if unset
            # NOTE: fields with a default value of "" are NOT excluded, since this is a valid value for some variables
            # (and an empty string value is different from the variable being unset)
            config.model_dump(by_alias=True, exclude_none=True).values()
        ):
            if section_num > 0:
                # Add a newline after each section for readability
                # TODO: Can add section headers as comments
                env_file.write("\n")
            for key, value in section_vars.items():
                env_file.write(f"{key}={value}\n")
