import configparser
import json
from pathlib import Path

from .logger import log_error, logger
from .models import BaseProfile


def load_ini_as_dict(file_path: Path) -> dict:
    """Read an INI file and return its contents as a nested dictionary."""
    # NOTE: By default, when there are duplicate sections or keys, the last occurrence will be kept
    config = configparser.ConfigParser()
    # By default, keys are converted to lowercase - convert instead to uppercase to match the expected environment variable format
    # We need to silence an erroneous mypy error here (see https://github.com/python/mypy/issues/5062)
    config.optionxform = lambda option: option.upper()  # type: ignore

    try:
        config.read(file_path)
    except configparser.Error as err:
        log_error(logger, f"Error reading INI file: {err}")

    if not config.sections():
        return {}

    return {section: dict(config[section]) for section in config.sections()}


def config_to_env_str(config: BaseProfile) -> str:
    """Convert a deployment profile configuration to a string in the format of a .env file."""
    env_lines = []
    env_lines.append(
        "# This .env file was auto-generated by configure-nb. Do not edit this file directly."
    )
    # exclude_none is useful for experimental variables that we want to omit from the .env file if unset
    # NOTE: fields with a default value of "" are NOT excluded, since this is a valid value for some variables
    # (and an empty string value is different from the variable being unset)
    for section_vars in config.model_dump(
        by_alias=True, exclude_none=True
    ).values():
        # TODO: Can add section headers as comments
        for key, value in section_vars.items():
            env_lines.append(f"{key}={value}")
        env_lines.append(
            ""
        )  # Add a newline after each section for readability
    return "\n".join(env_lines)


def write_json(path: Path, data: dict):
    """Write a dictionary to a JSON file."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def write_text_file(path: Path, contents: str):
    """Write a string to a text file."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(contents)
